language: perl6
perl6:
  - latest
install:
  - sudo apt-get install libssl-dev
  - rakudobrew build-zef
  - zef --debug --depsonly install .
  - zef --debug --/test install IO::Socket::SSL
script:
  - prove -v -e 'perl6 -Ilib' t/
sudo: false
